### ISSUE TITLE
hitbox is strange on "create commit message"

### ISSUE THREAD

**Issue by djdevin** [unicorn-fail/dreditor#1]
Chrome 28

The "Create commit message" button can only be clicked when the mouse is in the lower 1/4th of the button.

"make sticky" does not behave this way.

**Comment by davereid** [comment]
I can confirm this behavior as well with Chrome 29 on Linux.

**Comment by markhalliwell** [comment]
Determined this is because of the absolutely positioned tags.

**Comment by markhalliwell** [comment]
I believe this is now fixed due to the D7 version of d.o putting the issue information on the edit page only.
