### ISSUE TITLE
Comment reference auto complete is not working

### ISSUE THREAD

**Issue by vijaycs85** [unicorn-fail/dreditor#120]
Sorry if it's a duplicate, but I don't see any open issue. 

Version: 1.2.5 / Chrome

When enter comment number with # and pressing tag usually adds the link reference to the comment before D7 upgrade. Since upgrade it stopped working.

**Comment by star-szr** [comment]
Thanks for the report! This was just fixed a couple days ago in 867ab37cccf02c8fd120662cfc9f50fed4f0f79d and will be in the next release of Dreditor :)
