### ISSUE TITLE
Suggested commit message is not handling quotes properly on issue title

### ISSUE THREAD

**Issue by heitoralthmann** [unicorn-fail/dreditor#13]
I have the following issue title:

_Adicionar "configure" link na lista de módulos_

And the generated commit message was:

_git commit -m "Issue #2087865 by halth: Added Adicionar 'configure" link na lista de módulos."_

As you can see, there's a wrong quote inside the commit message which is breaking the command.

**Comment by davereid** [comment]
This has already been fixed with #10 and #11.

**Comment by heitoralthmann** [comment]
I'm sorry. Didn't check closed issues :(
