### ISSUE TITLE
Save review comments in localStorage then remove once pasted

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#151]
Follow-up from #117.

I think it would be a good idea to save comments (per file url) until they're safely pasted. This could also have the added benefit of keeping comments in multiple files/reviews in case one needs to switch between them.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#30
