### ISSUE TITLE
Create an update system similar to hook_update_N()

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#154]
Follow-up from #153:

> The old form.backup storage key unfortunately cannot be cleaned up, as we do not have a update system yet (which would likely work similar to hook_update_N(), but we would use unix timestamps instead of arbitrary sequential numbers).

**Comment by markhalliwell** [comment]
I'm not sure about timestamps. We have version numbers, let's use those. We could easily have something like:

``` js
Dreditor.updates = {
  '1.2.6': []
};
```

And then some mechanism that would allow each plugin just push functions to the array. This would allow us to keep updates with the plugin file:

``` js
Dreditor.update('1.2.6', function () {
  // Remove old "form.backup" storage key here.
});
```

**Comment by markhalliwell** [comment]
Postponed on #157

**Comment by sun** [comment]
I like that idea.  To possibly advance on it:

We could leverage the fact that the dot syntax is actually **a thing** in JavaScript. :8ball: 

``` js
Dreditor.updates = {
  1: {
    2: {
      6: [callBack1, callBack2, ...]
    }
  }
}
```

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#29
