### ISSUE TITLE
Include packaged jQuery library with extensions

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#156]
One of the reasons Dreditor's extension didn't make it through https://addons.mozilla.org approval process is because they said we're "injecting 3rd party libraries" instead of "packaging it with the extension": https://github.com/dreditor/dreditor/blob/1.x/src/js/init.js#L11-L22

Currently we're also technically injecting the entire content script on the page itself as well: https://github.com/dreditor/dreditor/blob/1.x/src/js/_banner.footer.js

I would like to move more into a more towards a native extension's way to communicate with the browser's DOM: https://developer.chrome.com/extensions/content_scripts#host-page-communication

ref: #129

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#27
