### ISSUE TITLE
Make a plugin inject buttons

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#163]
related to https://github.com/dreditor/dreditor/pull/147

If we need multiple different buttons in a certain spot:

Merge the two buttons into a single plugin and make that plugin inject all buttons (give or take a wrapping container).

Split the button operations into separate methods on the behavior object (next to attach()); i.e., insertSummaryTemplate() + insertNoviceTasksTemplate().

This will help to prevent duplicate code, since we can abstract all common functionality into separate helper methods.

**Comment by sun** [comment]
Closing this one for now, since the revised code of #147 doesn't require follow-ups.
