### ISSUE TITLE
commit message button doesn't work on some issues

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#164]
Create commit message
button on https://drupal.org/node/2212283
does not work, it just goes to the top of the page (https://drupal.org/node/2212283#)

But on other issues like https://drupal.org/node/2246665
it works fine.

**Comment by markhalliwell** [comment]
Confirmed. The following error is visible in the JS console:
`Uncaught TypeError: Cannot read property '0' of null`

On line 760: `uid = $submitters[user].href.match(/\d+/)[0];`

It's trying to get the `0` index of a null match. The match should be wrapped in an `if` statement before continuing.

**Comment by sun** [comment]
This is caused by much heavier d.o breakage.  All user account URLs are aliased now.  We need to fix this + much more.

I'll create a new 1.2.7 milestone now to track + fix all affected code ASAP.

**Comment by YesCT** [comment]
maybe cause nod_ is in the issue?
