### ISSUE TITLE
Replace $.each with native for loops

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#166]
Follow up from #165:

> Using `$.each` is very [expensive](http://jsperf.com/browser-diet-jquery-each-vs-for-loop) when we're just needing to iterate over each item (also not recommended per Drupal's [jQuery coding standards](https://drupal.org/node/1720586#each)). I know there's a lot of these through out Dreditor, but we probably shouldn't be adding even more in (follow up should be created to convert existing ones).

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#24
