### ISSUE TITLE
issue.values plugin no longer works since D7 upgrade

### ISSUE THREAD

**Issue by sun** [unicorn-fail/dreditor#167]
Problem
- The issue.values plugin no longer works since d.o's D7 upgrade.

Background / Purpose
1. This plugin is similar to the issue.clone plugin.
2. However, issue values are not based on any specific original issue, but rather, just simply the last values that you entered for the last issue that you created.
3. If you're in the process of refactoring/fixing subsystem X, then it is likely that you're going to create multiple issues that share the same basic properties.
4. Hence this (simplistic) plugin.

Cause
- Just needs a fix to the primary/driving issue node add form selector.

Unclear
- Do we want to keep this plugin?

**Comment by markhalliwell** [comment]
> last values that you entered for the last issue that you created

If I understand that correctly, it always sets the values?

If that's the case, I think the issue.clone plugin is more of an acceptable solution because it's "opt-in".

**Comment by markhalliwell** [comment]
And my vote would be to remove `issue.values`
