### ISSUE TITLE
Create a higher level method to extract data attributes (with a defaultValue)

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#172]
Follow-up from https://github.com/dreditor/dreditor/pull/165#discussion_r13028805:

> This should probably use the more modern [dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.dataset) with fallbacks, like:
> `id: parseInt(this.dataset && this.dataset.uid || this.getAttribute('data-uid') || 0, 10),`

Upon further thought, I think it'd be nice to have something like (off the top of my head, probably not complete):

``` js
Dreditor.getData = function (element, key, defaultValue) {
  element = element instanceof jQuery ? element.first().get(0) : element;
  var value = element.dataset && element.dataset[key] || element.getAttribute('data-' + key) || null;
  defaultValue = defaultValue || null;
  switch(typeof defaultValue) {
    case 'number':
      // Determine whether value is an integer or float.
      // @see http://stackoverflow.com/a/3886106/1226717
      var float = parseFloat(defaultValue);
      var int = parseInt(defaultValue, 10);
      value = float == int && !isNaN(defaultValue) ? parseInt(value, 10) : parseFloat(value);
      break;
  }
  return value || defaultValue;
};
```

**Comment by markhalliwell** [comment]
That's right, `default` is a reserved keyword. Updating snippet.

**Comment by sun** [comment]
Doesn't this duplicate jQuery.data() to some level of extent...?

**Comment by markhalliwell** [comment]
Kind of, but not really. `$.data()` is really it's own hot mess. Yes, it retrieves data (then caches it internally), but it also sets data (which is also just updating the internal cache).

**Comment by markhalliwell** [comment]
This also takes into account a `defaultValue` which isn't even possible with `$.data()`.

**Comment by markhalliwell** [comment]
I take that back. It is possible: `var uid = $element.data('uid') || 0`.

However, if `data-uid` is set it would return `"12345"` as a string instead of `12345` as an integer.

**Comment by markhalliwell** [comment]
There is also some issues around which version of jQuery is running and how `$element.data()` sets it's keys for the data attributes: https://josephscott.org/archives/2011/05/html5-spec-calls-for-altering-your-data/

This is also more reason for implementing #156.

That being said, I think there just needs to be a way to consistently access this stuff. In some places we're using native DOM properties and in others we're using jQuery. I don't care which one we do, I was just trying to help make things consistent.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#23
