### ISSUE TITLE
Remove jQuery UI dependency

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#173]
Follow-up from #156 and IRC discussion.

The reason the jQuery UI dependency was added was to make the left bar and patch review area resizable for long ass PSR-0 filenames (https://drupal.org/node/2026847).

With the accepted direction of PSR-4 (https://drupal.org/node/1971198 & https://drupal.org/node/2083547), this may no longer be an issue.

However I am not entirely sure we want to remove this ability. I have found that resizing sometimes needs to happen, especially when switching between my desktop monitor (large) and my itty-bitty MacBook Air screen.

**Comment by markhalliwell** [comment]
Sorry, accidently created issue before finishing the summary.

**Comment by sun** [comment]
I assume that most users are not even aware that the bar is resizable in the first place (I wasn't).

Supporting that is a bit overkill... Instead, I'd recommend to be smart and automatically figure out the _optimal_ width of the sidebar & code pane.

The maximum necessary width of the sidebar is the longest filename in the jump menu.  The minimum required width of the code pane is the 80 chars delimiter (+ ~10 chars).

**Comment by markhalliwell** [comment]
The original "fix" was simply to make the sidebar jump menu's `overlow-y: auto;`. I just took it a step further to make it "adjustable" because, as stated above, there are use cases (screen size changes) where I feel it's necessary.
