### ISSUE TITLE
Patch name suggestion seems broken

### ISSUE THREAD

**Issue by clemens-tolboom** [unicorn-fail/dreditor#181]
On FF Dreditor 1.2.6 and 1.2.7 does add a hash like https://drupal.org/node/1934498# instead of something useful.

Same goes for Chrome Dreditor 1.2.7

**Comment by markhalliwell** [comment]
Indeed, this is definitely broken: https://github.com/dreditor/dreditor/blob/1.x/src/js/plugins/issue.js#L13-L21

I'll submit a PR shortly to fix this.
