### ISSUE TITLE
Create issue follow-up buttons

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#184]
Originally the "clone" button was created to facilitate this need, however in hindsight, the word "clone" does mean an _exact_ copy.

What we often have in issues are follow-ups that need to be created after discussion of the issue has reviled more pieces of the puzzle. This helps prevent the current issue from becoming "scope creeped".

We could utilize and expand the existing [bare issue summary template](https://drupal.org/node/1326662):

Before any issues have been created (missing `[#N]` inside the `<li>`):
![create](http://monosnap.com/image/8b6CdPannUDOMjHPRjJZYSxYTK14f2.png)

After an issue has been created (`[#N]` present inside `<li>`):
![created](http://monosnap.com/image/XvB6F6pX7ihKi5An82i0mg3uhYI7Ry.png)

cc/ @yesct

**Comment by sun** [comment]
> the word "clone" does mean an exact copy.

"Clone" just describes the technical operation... Of course, no one is supposed to clone/copy an existing issue into a new issue _identically_ (without adjusting it to be a prerequisite or follow-up relative to the originating issue).

What's proposed here looks nice, but will require very complex code to reliably parse a free-form issue summary markup - as well as editing/manipulating the raw text in-place (which involves to parse a unfiltered, textual representation of a DOM fragment)...  Even if we manage to do that (somehow), it's going to be a lot of code to maintain for little benefit.

Such manual, textual lists of subtasks are suboptimal to begin with... they are duplicating the whole purpose of issue relationships, which can be properly categorized and are machine-readable (to e.g. build dependency graphs).

A better way to approach this would be to adjust d.o itself to allow to maintain a list of subtasks that do not have an issue relation attached to it.

**Comment by markhalliwell** [comment]
Just an idea. Postponing for now.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#20
