### ISSUE TITLE
patch review completely broken since last update

### ISSUE THREAD

**Issue by joachim-n** [unicorn-fail/dreditor#2]
I updated today to the latest version, and now patch review is totally broken.

When I click on the review button, I get a LH sidebar that says 'Diff outline' but other than that, the issue page is unchanged.

I am on the latest Firefox on OS X 10.6.

**Comment by markhalliwell** [comment]
Did you try removing the old script before installing?

**Comment by joachim-n** [comment]
No.... was I meant to? Didn't see anything telling me to do that; the whole process was just like any other dreditor update.

**Comment by joachim-n** [comment]
Ah, that fixes it.

**Comment by markhalliwell** [comment]
There was a note below the install button (for existing Chrome users) letting people know that you should remove the old script. I've generalized this for all users migrating from the d.o project.

**Comment by markhalliwell** [comment]
I also moved it between the "Install Dreditor" header and the button to make it more noticeable. Thanks for bringing this to my attention!

**Comment by scor** [comment]
I ran into this too. I bet a lot of people will do. I guess there is no way to display a warning when people try to upgrade and haven't deleted their old version of dreditor?
