### ISSUE TITLE
Enhance aesthetics and readability of colorized diff

### ISSUE THREAD

**Issue by jtwalters** [unicorn-fail/dreditor#20]
Rather than coloring the type green/red, I think the background color alone and a dark gray type makes the diff more aesthetically pleasing to read.

Specifically, `#dreditor #code .old` and `#dreditor #code .new` could use `color: #444`

![screenshot_58](https://f.cloud.github.com/assets/153132/1210266/7608d43c-25f7-11e3-804c-43b9b10026a5.png)

**Comment by markhalliwell** [comment]
Lol, I've gone back and forth on this topic with a few people. Some like it colored, others don't. I really don't know what to do here actually. However, I think keeping in-line with GitHub styles (dark gray) is probably preferable. Idk. If you submit a PR, please do one for both the 1.x and 2.x branches. Thanks!

**Comment by jtwalters** [comment]
See PR in #21 (2.x), #22 (1.x)
