### ISSUE TITLE
grunt watch:ff fails

### ISSUE THREAD

**Issue by clemens-tolboom** [unicorn-fail/dreditor#201]
Reading https://github.com/dreditor/dreditor/blob/1.x/CONTRIBUTING.md

> Requires the Firefox Add-on SDK, which should have been installed by the initial Setup already.

I'm not sure the **initial Setup** did it's proposed job.

```
Running "autoload:ff" task
Warning: Auto-loading release/firefox/dreditor.xpi failed: (4) Error: --2014-06-07 11:49:06--  http://localhost:8888/
Resolving localhost... ::1, 127.0.0.1, fe80::1
Connecting to localhost|::1|:8888... failed: Connection refused.
Connecting to localhost|127.0.0.1|:8888... failed: Connection refused.
Connecting to localhost|fe80::1|:8888... failed: Invalid argument.
```

Even running `brew install mozilla-addon-sdk` did not fix this.

What's wrong?

**Comment by markhalliwell** [comment]
There was a new step that was added `grunt install` which installs the FF add-on SDK.

I would recommend removing the `./tmp` directory (which is where it puts it, you may have an outdated/incorrect version).

That being said however, that does not seem to be the issue with that warning. It appears that either FF or the extension isn't allowing the connection. I had to double check that the extension was installed and working properly first https://addons.mozilla.org/en-US/firefox/addon/autoinstaller/#addon-description.

**Comment by sun** [comment]
@Cottser Were you able to resolve this in the meantime?

`grunt install` should download and supply the mozilla-addon-sdk in the expected location.

There's only a known issue with the SDK's `activate.bat` script on Windows, but it doesn't seem like you're on Windows.

**Comment by star-szr** [comment]
I'm all good, ask @clemens-tolboom :)

**Comment by clemens-tolboom** [comment]
Doh ... FF needs https://addons.mozilla.org/en-US/firefox/addon/autoinstaller/
