### ISSUE TITLE
Add option to add a selection of issue contributors

### ISSUE THREAD

**Issue by clemens-tolboom** [unicorn-fail/dreditor#203]
In plugin/commit.message.js we still have a TODO

> // @todo Rethink algorithm for crediting top commenters.

In https://assoc.drupal.org/comment/8373#comment-8373 John_B likes to get mentioned if only reviewing a patch or testing. I myself am getting less motivated to test patches for similar reasons. As an example https://drupal.org/node/2278507 should have more people mentioned then just 1. (Issue is personal :p and for reference as there where status changers, summary updaters and reviewers)

Maybe we could join this change with http://buytaert.net/a-method-for-giving-credit-to-organizations-that-contribute-code-to-open-source ?

Currently it's possible to select the author so why not be able to add others?

Suggesting those users would help people to select them.
- [ ] is this useful?
- [ ] is this necessary?
- [ ] we need an user interface.
- [ ] can we gather (a matrix of) all participant)?
- [ ] can we define an algorithm making more people happy?

**Comment by fabianx-ai** [comment]
I would second that and I would propose to do two things here:

a) Have a standard format for suggested issue commit message and use that one, together with a _red_ mark that says "Contributors have been selected from suggested commit message. Ensure that this is up to date with tags shown above."

b) A contributor that thinks they contributed, marks there POST with:

[x] REVIEWED or [x] CONTRIBUTED

or such and dreditor parses for such magic tags.

Both would solve that issue elegantly.

**Comment by markhalliwell** [comment]
I would much rather fix this on d.o directly, see https://www.drupal.org/node/2295411#comment-8939091

**Comment by clemens-tolboom** [comment]
Thanks for the link. I agree :)
