### ISSUE TITLE
Dreditor disabled on Chrome

### ISSUE THREAD

**Issue by yktdan** [unicorn-fail/dreditor#205]
Today Chrome changed to not allow browser extensions that do not come from the Chrome store. It won't allow reenabling it.

**Comment by markhalliwell** [comment]
This isn't an issue. Dreditor _is_ on the Chrome store: https://chrome.google.com/webstore/detail/dreditor/dhdpoembhlojpmehepeadblhglloobao. https://dreditor.org also uses that store ID to allow one click installation.
