### ISSUE TITLE
Make issue link tab-completion work with www prefix

### ISSUE THREAD

**Issue by xjm** [unicorn-fail/dreditor#210]
As of the latest Drupal.org changes (adding the www domain prefix to all URLs), tab completion of issue links no longer works. To reproduce:
1. Paste https://drupal.org/node/1825952 in an issue comment and press tab with the cursor at the end. It is automatically converted to [#1825952].
2. Paste https://www.drupal.org/node/1825952 and press tab. Nothing happens.

**Comment by markhalliwell** [comment]
This is already fixed. A release just hasn't been made yet. 

Typos courtesy of Siri

**Comment by xjm** [comment]
Found https://github.com/dreditor/dreditor/pull/207, thanks!
