### ISSUE TITLE
Remove "Content Scope Runner" hack

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#215]
This is legacy cruft from the user script days:
https://github.com/dreditor/dreditor/blob/1.x/src/js/_banner.header.js
https://github.com/dreditor/dreditor/blob/1.x/src/js/_banner.footer.js

This is also considered "3rd party injection" along with jQuery UI (#173) by mozilla and now antivirus programs? (#214).

**Comment by sun** [comment]
Requires #155 - or rather its implications - to get resolved first.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#13
