### ISSUE TITLE
Impossible to install from dreditor.org on a browser that doesn't already have Dreditor installed

### ISSUE THREAD

**Issue by DavidRothstein** [unicorn-fail/dreditor#221]
Steps to reproduce:
1. Get a browser that doesn't already have the Dreditor extension installed.
2. Go to https://dreditor.org/
3. Watch the "Determining latest release" text and spinning icon appear on the screen forever.  You are never given an opportunity to install the software.

I have reproduced this in both Firefox and Chrome.  In Firebug, the console shows an error message pointing to line 34 of https://cdn.dreditor.org/sites/default/files/js/js_P7RE5I8efXJn84h_laNXTsbSIwGyP0_f_kSNTWUCy9k.js and says "TypeError: v1.split is not a function" (in reference to the following code: v1parts = v1.split('.');).

The Chrome debugger points to the same line, but gives a less helpful error message.

It looks like the issue is that versionCompare() function in the JavaScript is being passed a non-string value ("false") for one of the versions but can't handle that.

**Comment by DavidRothstein** [comment]
Not sure how to indicate that this is a critical bug, but it is...

**Comment by markhalliwell** [comment]
This has been fixed on https://dreditor.org. Thanks!

**Comment by DavidRothstein** [comment]
Thanks for the amazingly fast turnaround time!  This works on Chrome, but there are still problems on Firefox.

I filed a new issue (in the right queue this time) here: https://github.com/dreditor/dreditor.org/issues/16
