### ISSUE TITLE
Use IndexedDB (with localStorage fallback)

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/dreditor#224]
With the deployment of [semi-]RESTws on d.o, there are new "official" API guidelines (https://www.drupal.org/about-drupalorg/api):

> Please use Drupal.org’s APIs respectfully.
> - Use an appropriate user agent string.
> - Make requests from a single thread.
> - Cache results locally whenever possible.
> 
> Abuse will be blocked as needed.

If we really want to utilize the new APIs on d.o (effectively), it would benefit everyone to cache data in Dreditor where appropriate (users, comments, files, taxonomy terms... maybe some parts of an issue node). Unfortunately, we are currently [greatly limited](http://en.wikipedia.org/wiki/Web_Storage#Storage_size) in how much we can store (max 5MB).

I propose that we adopt the use of [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). It's saturation already includes Chrome and Firefox, but not [ Safari](http://caniuse.com/indexeddb). Safari 8 includes support for this and will be out this fall.

Possible solutions:
1. Go ahead with pure IndexedDB integration and just wait for Safari 8 to come out.
2. Use a framework to help with graceful degregation of APIs, like: http://brian.io/lawnchair/

xref: #32, #154

**Comment by sun** [comment]
Perhaps it's just me, but I'd much rather prefer to change the HTML markup on d.o itself so as to produce machine-readable output — either via custom `data-` attributes, or microdata/microformats, or RDFa (whereas the latter two would generally [improve d.o's appearance in search results](https://support.google.com/webmasters/answer/99170?hl=en)).

Just like we recently added the `data-uid` attribute to all username links on d.o, that approach drastically improves the performance of Dreditor as well as all other tools that are trying to parse d.o issues.  No need for separate HTTP requests, separate web service APIs, or any custom client-side caches (that need to be maintained manually; i.e., a Last-Modified date change must trigger cache invalidations).

**Comment by markhalliwell** [comment]
Actually, we need a combination of the two. There are going to be use cases where parsing the DOM is appropriate and (in some cases) faster depending on what is trying to be accomplished. However, in cases like your issue triage, I can see this (IndexedDB) and d.o's new "REST" APIs being very, very beneficial.

**Comment by markhalliwell** [comment]
Granted, d.o doesn't (yet) allow full REST capabilities (i.e. PUT, DELETE, etc), but being able to simply pull a node's data (without the full HTML markup) has its uses, of which, is smaller and (generally) faster requests.

**Comment by sun** [comment]
Speaking of the RESTful API — we shouldn't need to maintain any kind of custom client-side cache/DB, if the server's HTTP responses have the correct HTTP headers to be cacheable.

If implemented correctly on both the server-side and client-side, the web browser/client will include an `If-Modified-Since` header in its request, and if the data was not modified, the server will just return `304 Not Modified` (without body), which causes the client/browser to serve the cached response from its regular built-in HTTP cache.

I.e., standard HTTP caching.

**Comment by markhalliwell** [comment]
> If implemented correctly on both the server-side and client-side

Yes. However, d.o does not apparently have this currently (likely in the future though).

https://www.drupal.org/api-d7/node/2317551.json will return `200 OK` every time.

And I'm not saying that this is for storing a strict cached version of d.o sends us. These usually do not contain the structure we would need anyway. Currently all that you see in node JSON is entity IDs. It doesn't (yet) actually include useful information, like: the actual taxonomy names, user names, file names, etc. This all could change in the future, but to determine these you'd have to do multiple requests.

Things like files, taxonomy terms and users do not or rarely change. We _should_ cache these; there is no point in sending a request all the time.

Also, we could implement a max cache time (i.e. 30 days or something) perhaps even specific to the entity: users 30 days, taxonomy and files forever.

This really has little to do with the node/issues themselves, but more about the meta data that is associated with them.

I'm not entirely sure, but I thought it would be beneficial for us to think about this at the very least.

**Comment by markhalliwell** [comment]
Also, I was envisioning this to help with issues like #93 (macros), #59 (themes, essentially) and even potential custom plugins... all of which would put a severe burden on or even exceed the localStorage capacity (over time).

**Comment by markhalliwell** [comment]
I know I started this by reasoning d.o integration; that was simply the catalyst. Given this is more about how Dreditor itself handles storage in general, I've removed that label (which is really #55).

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#10
