### ISSUE TITLE
Links in #nav-header is not accessible because covered by #header-content

### ISSUE THREAD

**Issue by RoSk0** [unicorn-fail/dreditor#225]

**Comment by markhalliwell** [comment]
This isn't a Dreditor issue, nor does it seem to be a drupal.org theme/site issue. Perhaps you have a user style override applied that needs updating.

**Comment by RoSk0** [comment]
Sorry for the noise. Completely forgot that I ever used user styles. It was [drupal.org unleashed](https://userstyles.org/styles/11133/drupal-org-unleashed).

**Comment by markhalliwell** [comment]
FWIW, I can confirm that it is indeed this particular user style; although I don't usually have it enabled personally.

cc/@sun

**Comment by sun** [comment]
Thanks, yeah, I'm aware of that.  I only wish userstyles.org had a proper issue tracker per style or GH integration or any kind of web service API… :stuck_out_tongue_winking_eye:
