### ISSUE TITLE
Order of commit credits is wrong in Safari

### ISSUE THREAD

**Issue by star-szr** [unicorn-fail/dreditor#226]
Examples:
https://www.drupal.org/node/2295469#comment-9096717
https://www.drupal.org/node/2314599#comment-9088063

Firefox and Chrome don't have this issue as far as I can tell.

Tested with Safari 7.0.6. on OS X 10.9.4.

**Comment by markhalliwell** [comment]
I feel I should point out the following issues in case we'd rather want to postpone/close this in favor of those instead:
https://www.drupal.org/node/2323715
https://www.drupal.org/node/2288727
https://www.drupal.org/node/2295411

**Comment by webchick** [comment]
Well, none of those feel like they're going to get deployed especially quickly, and since I've been messing up commit messages left and right for the past ? period of time, it'd definitely be awesome if we could get a quick fix for this. I'll use Chrome in the meantime.

**Comment by star-szr** [comment]
I started debugging it this morning but had to run to work. I think we need to fix the bug.

**Comment by markhalliwell** [comment]
Sure :)

Typos courtesy of Siri
