### ISSUE TITLE
latest 1.2.11 version not available as a .xpi in the releases section

### ISSUE THREAD

**Issue by klonos** [unicorn-fail/dreditor#230]
https://github.com/dreditor/dreditor/releases

**Comment by star-szr** [comment]
Thanks, fixed!

https://github.com/dreditor/dreditor/releases/tag/1.2.11

**Comment by klonos** [comment]
Thank you!

**Comment by markhalliwell** [comment]
@klonos, sorry. I forgot this process. I'll update the RELEASE.md page to reflect this so I don't forget it in the future.

FWIW though, https://dreditor.org will allow you to down the latest XPI on the front page if viewing in FF.

**Comment by klonos** [comment]
Last time I checked it was always prompting for installation instead of download. Trying with a different browser said you need firefox. And it is not available at AMO either where every addon has their own old versions section.

I always test dev versions of firefox/thunderbird and their addons if they have one available, so along the way I developed a habit to always keep a local copy of at least two versions back of every addon I use. Just so I can revert when things get messy.
