### ISSUE TITLE
Failing both install and update from dreditor.org to Firefox browser

### ISSUE THREAD

**Issue by tsvenson** [unicorn-fail/dreditor#252]
For quite some time I have had problems updating to a newer version of Dreditor from the site. Basically what happens is the following:
1. Dreditor notifies my about a new version, I open the site
2. https://dreditor.org/install shows the new version and I click update
3. I click "Allow" to download and install the new version
4. I immediately get a message saying that "The add-on could not be downloaded because of a connection failure on dreditor.org"

Before a workaround was to manually delete the old local version and then I could install the latest version. Now this is not possible either and I can't find any information about how to download the script and the install it manually.

How can I get around this problem?

**Comment by star-szr** [comment]
Thanks for the report, which version of Firefox and which OS? Are you behind a proxy, VPN, or similar?

**Comment by tsvenson** [comment]
I'm on Win 7 and using all the latest version. No proxy or VPN.

Have had this problems for many months now. Is there a way I can snoop on the communication and find more useful information to better identify what is actually going wrong here?

**Comment by interdruper** [comment]
In my case the origin of the problem was the Avast Antivirus, who is not very 'friendly' with DrEditor (don't ask me why...)
Just disable for a moment all the Avast shields, and install on Firefox as you tried.
Hope it helps.

**Comment by star-szr** [comment]
Thank you @interdruper!

**Comment by tsvenson** [comment]
Confirming I was using Avast when having the problem. Now upgraded that machine to Ubuntu instead ;)

**Comment by star-szr** [comment]
@tsvenson thanks for reporting back!

@markcarver any objection to us documenting this as a known conflict? Not sure where we would do that exactly but just a thought.

**Comment by markhalliwell** [comment]
Done. I have updated the homepage of https://dreditor.org to include an "Anti-virus software" alert message at the bottom linking to this issue.
