### ISSUE TITLE
The 80 chars guide is 1 char to the left

### ISSUE THREAD

**Issue by claudiu-cristea** [unicorn-fail/dreditor#260]
As we are reviewing patches and patches lines have 1 char prefix, the vertical guide must be draw after the 81st character. Right now it's drawn after 80 chars and this can lead to the conclusion that some lines are not correctly wrapped.

The snapshot example is from https://www.drupal.org/node/2281533#comment-10201329

<img width="826" alt="80chars" src="https://cloud.githubusercontent.com/assets/473868/9157140/fa76ee48-3efa-11e5-9f50-b102d1aba5af.png">

**Comment by star-szr** [comment]
I think I narrowed it down to when a new file is added that is 100 lines or more, and when no changes are made to other files outside of the first 99 lines. The ruler calculation falls apart in that situation, looking at the code now.

**Comment by star-szr** [comment]
This is fixed in Dreditor 1.2.15 which was just released. Thanks for the report!
