### ISSUE TITLE
Provide an enhanced drag and drop file upload widget

### ISSUE THREAD

**Issue by stefanruijsenaars** [unicorn-fail/dreditor#263]
The drupal.org file upload widget is a bit small so when dragging and dropping patches we have to "aim" for the right spot, and click the upload button afterwards as well.

Would it make sense to make the upload widget slightly bigger and automatically upload when a file is dragged into it, as opposed to having to click the upload button?

**Comment by star-szr** [comment]
@stefanruijsenaars thanks for the idea. I think this should be implemented directly in drupal.org, see https://www.drupal.org/project/drupalorg.
