### ISSUE TITLE
Provide link from comment #1 to current issue summary

### ISSUE THREAD

**Issue by sja45uk** [unicorn-fail/dreditor#271]
When reviewing the issue queue, the Summary field links to the top of the issue page. If the issue has been updated then the "N new" in the Replies field links to the #new comment. It would be helpful (when viewing an issue that has not been viewed before) if the comment #1 gave easy access to the start of the issue summary. Perhaps the dreditor could provide a link from comment #1 to the "page-subtitle" h1 tag. This would avoid the need to unnecessarily scroll the browser to view the summary.

**Comment by star-szr** [comment]
Hi @sja45uk, thanks for the suggestion! At this time we're generally not interested in adding these types of tweaks to Dreditor itself, it's much easier these days to get these types of changes into drupal.org directly where everyone can use them, regardless of whether they use Dreditor (or whether their browser/device even supports browser extensions).

**Comment by sja45uk** [comment]
Makes sense to put something into the base page, but I am not sure how easy that will be to achieve as it affects all visitors. Is it feasible for me to fork dreditor to introduce an experimental change to help me decide if an additional link from each comment would be useful.

Sent from my Windows Phone

**Comment by star-szr** [comment]
I'm a bit confused now I thought this was just for comment #1 based on your description. So is it more of a "back to top" link?

Yes, it's easy to fork this repository and there are instructions for building the code into extensions in CONTRIBUTING.md.

**Comment by sja45uk** [comment]
Scott - My original requirement was to go from the Comment #1 up to the issue summary. It became apparent to me from your reply that there were two options: change D.o issue display; or change dreditor. As I thought further about a fork to dreditor, I decided that a back to issue summary from every comment would probably better meet my needs. So the inevitable requirements drift has struck. Steve

**Comment by star-szr** [comment]
Gotcha. I know it's not quite the same but don't most browsers let you go to to the top of the page by pressing <kbd>Home</kbd> on the keyboard?

**Comment by sja45uk** [comment]
I guess I should try Home then PgDn to see if it satisfies the use case. Unfortunately the Issue Summary starts more than half way down the screen.
