### ISSUE TITLE
Drupal.dreditor.issue.getNewCommentNumber() is not returning the correct comment number

### ISSUE THREAD

**Issue by alexpott** [unicorn-fail/dreditor#280]

**Comment by alexpott** [comment]
This is because of the new code filter on d.o... it adds the following html
`<span class="token comment" spellcheck="true">// Prefix and suffix used for Ajax replacement.</span>`

**Comment by star-szr** [comment]
@alexpott thanks, example issue link please? I can't find one that's broken so far. And just in case, what browser and version are you using?

**Comment by alexpott** [comment]
https://www.drupal.org/node/2346893#new

<img width="367" alt="screen shot 2016-03-30 at 14 48 26" src="https://cloud.githubusercontent.com/assets/769634/14144163/887dbac6-f686-11e5-9714-ddc1a0e99473.png">

Chrome Version 49.0.2623.87 (64-bit)

**Comment by star-szr** [comment]
Was able to reproduce this with that issue, thanks. Manual testing before/after checks out and the PR (#281) seemed quite safe so it has been merged. Thanks for this!
