### ISSUE TITLE
Display latest user comments

### ISSUE THREAD

**Issue by mootari** [unicorn-fail/dreditor#284]
I am currently using a custom user script that loads a user's last 5 comments into his or her profile page via drupal.org's Rest API.  This helps in determining e.g. if a maintainer is still active or what topics a user has been working on recently.

If you don't consider such an (optional) feature out of scope for dreditor I'd be happy to polish the script so that it can be integrated.
By the way, a common wrong assumption is that the "Posts" tab provides the same feature. This is not the case, as it shows posts a user follows, ordered by the most recent updates - regardless of who or what caused the update.

Here is an example from my own profile page:

<img width="694" alt="profile-comments" src="https://cloud.githubusercontent.com/assets/322014/14767700/bf528a18-0a2c-11e6-8ecc-38d131365506.png">

**Comment by star-szr** [comment]
Cool feature! In general we are trying not to add features like this to Dreditor that would probably be best implemented on Drupal.org directly and be of benefit to more folks (and more devices). Thanks for the offer though 👍
