### ISSUE TITLE
Clone issue link broken on issue pages

### ISSUE THREAD

**Issue by naveenvalecha** [unicorn-fail/dreditor#289]
Steps to reproduce : 
1. Go to any issue link https://www.drupal.org/node/2765231
2. Click on the Clone issue button
3. It will take to https://www.drupal.org/node/add/project-issue/**undefined**#project-issue-node-form which is 404

Reason I found from my debugging : The js is not able to fetch the project name https://github.com/unicorn-fail/dreditor/blob/adfc2b2b02a1cba242512bd7ccde35aafe62c058/src/js/plugins/issue.clone.js#L14

**Comment by mglaman** [comment]
Yeah, this is making issues on Contrib Tracker a pain

**Comment by naveenvalecha** [comment]
As the html structure has been changed of the breadcumbs on the d.o. from <div> tag to <nav> tag. So the clone.js also needs fix

**The fix** 

https://github.com/unicorn-fail/dreditor/blob/adfc2b2b02a1cba242512bd7ccde35aafe62c058/src/js/plugins/issue.clone.js#L14
Change this line to 

`var project = /[^/]*$/.exec($('nav.breadcrumb').find('a').attr('href'))[0];`

Can someone test and raise the PR

**Comment by star-szr** [comment]
There is already a PR - please test #290.

**Comment by star-szr** [comment]
Fixed, working on making a new release now.

**Comment by star-szr** [comment]
Having trouble with the automated builds, stay tuned.

**Comment by star-szr** [comment]
We have 1.2.17 for Chrome and Firefox up (Chrome will autoupdate, for FF visit dreditor.org and good luck) but Safari is giving us trouble.

Closing this issue. If/when we resolve the Safari extension issue Safari will autoupdate anyway.
