### ISSUE TITLE
Problem installing on Safari

### ISSUE THREAD

**Issue by jmburnz** [unicorn-fail/dreditor#3]
I installed NinjaKit and it is installed, but when I click the install button for Dreditor on dreditor.org it just loads the raw JS in the browser.

Safari 6.0.5 on OSX 10.8.4

**Comment by markhalliwell** [comment]
Dreditor now has a native Safari extension! Visit http://dreditor.org with a Safari browser. It is no longer necessary to use the NinjaKit extension. You should at the least remove the Dreditor userscript used in NinjaKit or remove NinjaKit entirely if Dreditor is all you used it for.

Updates are now also managed via Safari (either manually in the extensions tab in preferences or automatically by Safari). Once you install it the new extension, you won't have to click the button again.

**Comment by jmburnz** [comment]
Awesome, thanks very much for the update, all working now.
