### ISSUE TITLE
Drupal.org on Drupal 7

### ISSUE THREAD

**Issue by helmo** [unicorn-fail/dreditor#34]
Hi,

I was wondering if there has been any work done on the Drupal 7 dev sites for Drupal.org.

https://git7site.devdrupal.org/

Adding two include lines : 
// @include        _://devdrupal.org/_
// @include        _://_.devdrupal.org/*

would do the trick to start testing... but the 2.x branch seems to lack these include lines. Any hint on how that works?

**Comment by markhalliwell** [comment]
Committed so far, please test:
088d26dcd267b0973e626df2eb74245343683b72 Initial conversion of Dreditor to utilize new D7 attachBehavior objects.
3582edb4762cf5fadc694aff39e4d0bfcc7d793d Fixed sort order, fixed patch review and commenting.

**Comment by markhalliwell** [comment]
I am closing this issue as I'm pretty sure we have a solid migration for d.o d7's upgrade. Please follow the instructions at http://lb.cm/dreditor-dev to test... however a release will be immanent later this evening before d.o comes back online. Any new problems found should have a new issue created, **DO NOT** comment on this issue to report problems. Thanks!
