### ISSUE TITLE
Uncaught TypeError: Cannot call method 'getIssueTitle' of undefined

### ISSUE THREAD

**Issue by podarok** [unicorn-fail/dreditor#36]
https://drupal.org/node/1139088
Got this here and not only when pushing "Create commit message" button
Google Chrome 30.0.1599.69 on win32 XP
dreditor 1.1.7

**Comment by podarok** [comment]
Sorry, my fault
old dreditor should be removed via chrome://extensions

**Comment by vladdancer** [comment]
Hm.. It's ok for me. Could you please write steps to reproduce this bug?
Google Chrome 30.0.1599.69 m on Windows 7
Chromium Version 28.0.1500.71 Ubuntu 12.04
dreditor 1.1.7

**Comment by vladdancer** [comment]
Oh) It's already closed)
