### ISSUE TITLE
Hard to copy and paste code (selection/comment toggle)

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#37]
http://screencast.com/t/oIiYtqaOHA

If I want words 5-8 in a line, I click at the beginning of the 5th word, then drag to the end of the 8th, then let go.

I expect to have those words hidden.
Instead I have "marked" that line and nothing is selected.
then I have to do it again.
this is annoying.

Is it solvable?

**Comment by star-szr** [comment]
A more intentional interface for code review (for example with markers in the gutter to click on/drag/whatever) might be a way of solving this. I agree it's annoying.

**Comment by markhalliwell** [comment]
There's a lot of logic behind how the "selection" (for line comments) is done. This mainly involves mouseup/mousedown/mousemove events bound to each table row. TBH, I'm not really how this could be solvable. If we focus on making partial selection in a line the focus, we'll probably end up breaking the line commenting functionality (or just really end up confusing people). Perhaps we can make it entirely non-selectable? We can always open the raw patch in a new window if we need specific text.

Another solution (which would require a complete redesign of the patch review process), would be to show the lines selected with the comment box (like a "preview" of what would be shown in the comment) which you could copy from. I'm not entirely sure how that would work, but it would likely entail separating "comments" into another pop-up so we can have the full screen for both the selection & comment (cause it really wouldn't fit in that tiny sidebar).

**Comment by star-szr** [comment]
Basically I am thinking it would be nice to have a clear difference between selecting text and choosing lines of code to review. Reworking this would probably easy allow us to close out tickets like #4. But in contrast to the implementations on e.g. GitHub and BitBucket it would be nice to retain the multi-line comment ability, I think that's really useful for patches. Or maybe we can dream up some way to make inline comments on patches a reality :)

I wonder what else is out there that allows multi-line comments. Maybe Differential in Phabricator? Doesn't look like it from the screenshots though.

**Comment by sun** [comment]
@fubhy and I actually had a very smart idea for how to resolve this at some DrupalCon, a long time ago.  The idea was extremely simple, but absolutely non-obvious.  It was 100% KISS, and I remember that I sat there and wondered why I didn't think of that before... ;)

Unfortunately, I forgot what that solution was in the meantime... I can only hope that @fubhy remembers.

**Comment by fubhy** [comment]
There are many ways of solving this and during Drupal DevDays Barcelona (that's when we discussed this @sun :)) what we came up with was very simple indeed: Keeping CTRL pressed would mute the magic "select for review" logic. So if you select something while pressing CTRL it would not automatically mark it. Additionally there could be a little button in dreditor where you could toggle the magic "select for review" on and off.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#41
