### ISSUE TITLE
Recent files in issue summary on D7 d.o wrap incorrectly

### ISSUE THREAD

**Issue by star-szr** [unicorn-fail/dreditor#40]
Link:
https://git7site.devdrupal.org/node/1304470

Before enabling Dreditor:
![dreditor-recent-files-before](https://f.cloud.github.com/assets/327943/1446432/12af970c-4237-11e3-8dda-6c0a3c5a4924.png)

After enabling Dreditor:
![dreditor-recent-files-after](https://f.cloud.github.com/assets/327943/1446437/1c73cf9c-4237-11e3-8eb6-313d44c66e6b.png)

**Comment by WesWedding** [comment]
Still seems to need work.  Firefox 25.0 in Win7.

![dreditor40-1](https://f.cloud.github.com/assets/521813/1451040/2b292d08-428b-11e3-8cbd-ec9eedf1ee4a.png)
