### ISSUE TITLE
Insert issue summary template button missing on D7 d.o

### ISSUE THREAD

**Issue by star-szr** [unicorn-fail/dreditor#43]
On issue node edit form.

Screenshot from D6 d.o:
![dreditor-insert-template](https://f.cloud.github.com/assets/327943/1446521/784d86c2-4238-11e3-8b99-05144d7394bf.png)

**Comment by YesCT** [comment]
related: https://github.com/dreditor/dreditor/issues/50
"issue summary button missing on node add (when creating a new issue)"
