### ISSUE TITLE
Bring back the [edit issue summary]

### ISSUE THREAD

**Issue by Bojhan** [unicorn-fail/dreditor#48]
On Drupal.org you now have to go to a seperate page to edit anything. Even the smallest thing. This workflow is modeled after implementation and not ease of use. 

Dreditor should bring all this functionality back in line, just like it did with the [edit issue summary] button. This will save people like me, who only do small stuff like uploading an image once in a while, and changing status many countless hours moving back and forth. 

Feel free to ping me to get a design.

**Comment by xjm** [comment]
I'd suggest having the little link on both the top and bottom of the form (by the button in the sidebar, and in the "Update this issue" header above the comment form).

**Comment by Bojhan** [comment]
Yes, I am not sure if this will be picked up by the Dreditor people. But it would make d.o usable again for me.

**Comment by sun** [comment]
https://drupal.org/node/2159813 has just been fixed, so the issue edit form is back on the node view page, which makes this issue obsolete, I guess.
