### ISSUE TITLE
For the new D7 Drupal.org, consider making the project status "card" fixed positioned.

### ISSUE THREAD

**Issue by cosmicdreams** [unicorn-fail/dreditor#49]
By adding these styles to the issue status card you can make it have a fixed position so that it is still present on the screen as you scroll.

[css]
.node-type-project-issue #aside {
  width: 31.91489%;
  margin-right: 0;
  display: inline;
  position: fixed;
  left: 65.95745% /\* same as #main */
}

**Comment by Bojhan** [comment]
Just wanted to let you know about http://userstyles.org/ 

Dreditor probably shouldn't mess too much with the actual styling of the issue queue, and provide mostly functional tools. For example, I prefer the card to be fixed on top and just full width the comments using my personal user style

**Comment by markhalliwell** [comment]
I agree that this should be a userstyle or even a "feature" request in https://drupal.org/project/issues/d7qa. Dreditor shouldn't add this.

see: https://drupal.org/node/2125589 and https://drupal.org/node/2128147
