### ISSUE TITLE
Large patches parse slowly

### ISSUE THREAD

**Issue by yched** [unicorn-fail/dreditor#5]
v 1.1.7 Chrome / Linux

On a issue like https://drupal.org/node/1497374 (200+ comments, many patches), dreditor adds like 7 / 8 seconds processing time after initial page load (that is, before JS behaviors / extensions like mouse gestures become available)

**Comment by markhalliwell** [comment]
I was able to load the page itself relatively fast (Chrome/Mac). It's the "FULL" patch in [#1497374-220](https://drupal.org/node/1497374#comment-7802529) that I see some serious latency issues. Granted that patch is over 600KB.

How Dreditor (currently) parses patches is _very_ slow. FWIW, I actually have plans to fix a lot of how Dreditor "loads" and "parses" in 2.0. Particularly looking at using native [FileReader](www.htmlgoodies.com/beyond/javascript/read-text-files-using-the-javascript-filereader.html) (if supported by the browser, with the current method as a fallback).

I've also even entertained the idea of using node.js, which would allow something like [this](http://stackoverflow.com/questions/12453057/node-js-count-the-number-of-lines-in-a-file) as another possible solution.

**Comment by yched** [comment]
Yeah, I kind of expect opening a patch review on a 600k patch not to be blazingly fast.

The delay on initial issue page load is more annoying :-). page goes back in "loading mode" (mouse pointer + spinner on the tab favicon) for around 8 seconds.

This being said, if you can't reproduce it...

**Comment by markhalliwell** [comment]
Oh and to also clarify my thoughts for how Dreditor "loads" in 2.0, my thoughts are this:
1. Scan all the initial comments for patches and queue just the URL (not actually loading them).
2. Upon clicking the "Review" button, launch the review overlay.
3. The patch clicked on would become automatically selected from the drop down that's in the review overlay (which would also allow easier toggling between patches/interdiffs without having to leave the review window).
4. Upon loading any of these patches in the review overlay, a "loading" progress indicator would then be shown to inform the user that the patch is being parsed.

Overall, smaller patches would still appear almost instantaneous, but for larger patches this would help alleviate some of the confusion about why it _appears_ that the browser has stopped responding.

In regards to the "initial" page load, I need to create a Linux test environment with Chrome & FF, but it's on my todo list and not exactly sure _when_ I'll get to doing that. I'm starting to wonder if there really is a lot of difference between the *nix versions of Chrome. Btw, what versions of both Chrome and Linux?

**Comment by yched** [comment]
Chrome is 29.0.1547.57
Linux is Kubuntu 12.04.3, kernel 3.2.0-52-generic

**Comment by markhalliwell** [comment]
Ok, running Chrome is 29.0.1547.57 on OSX 10.8.4 here. I'll see about setting up an [K]ubuntu env this weekend, hopefully :)

**Comment by yched** [comment]
OK, nailed it down to some chrome extension, completely unrelated...
Very sorry for losing your time :-(

**Comment by markhalliwell** [comment]
Oh you didn't waste my time :) I like that you're also concerned with Dreditor's performance. I want to keep this open though, so I can implement the other issues I mentioned above (which _are_ slow for larger patches).

**Comment by yched** [comment]
OK - so just to be clear, no perf worries on issue pages themselves (at least not that I know of :-p)
Review on large patch files, sure, different story.

**Comment by markhalliwell** [comment]
Yes :) I've updated the issue title to reflect this distinction.

**Comment by dawehner** [comment]
One random other example

**Comment by star-szr** [comment]
Large patches are indeed painful and we have a ways to go but #95 is a step in the right direction IMO.

**Comment by sun** [comment]
Out of curiousity, I clicked the "Review" button on the **15 MB** [phpunit upgrade patch](https://drupal.org/node/2114823)...

LOL, yeah. — 15 MB turning into **1.5+ GB** is definitely not fun.
(my system OOM'ed at 1.5 GB, so dunno how much more would have followed)

I need to spend some quality time on the _"prettified"_ patch reviewer code...
(i.e., the revamp that introduced diff line numbers + GitHub-alike styling)

There are a whole bunch of issues in there; e.g.:
1. Super-obvious CPU/memory disasters
   …e.g., binding multiple events on _every. single. line._ of the processed diff.
2. The innocent looking switch to a `<table>`
   …requires the browser to prepare the full layout of the rendered table in memory, before it is able to insert it into the DOM…  Followed by a full page layout reflow to re-apply CSS.  Yuck.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#54
