### ISSUE TITLE
Create commit message broken

### ISSUE THREAD

**Issue by swentel** [unicorn-fail/dreditor#52]
The 'create commit message' button doesn't account for all people who have worked on a patch. It seems to take only the name of the person who has created the issue.

examples:
https://drupal.org/node/2112705
https://drupal.org/node/2019055

**Comment by star-szr** [comment]
Thanks, this has been fixed in dev - see #45 and http://dreditor.org/development.

**Comment by star-szr** [comment]
1.2.1 is out now and contains this fix and a couple others.
