### ISSUE TITLE
Generated commit message does not include every user who provided a patch

### ISSUE THREAD

**Issue by amateescu** [unicorn-fail/dreditor#54]
This is a problem caused by the d.o migration to D7, and since a picture is worth a thousand words, here it is:

https://www.evernote.com/shard/s268/sh/0e611c97-21bc-4d09-8f6a-b972762d6e90/b187adccba64ba4c8bcc56601f103647

**Comment by star-szr** [comment]
Thanks, this was fixed in #45, expect a new release containing that fix very soon or you can use the [development release](http://dreditor.org/development) in the meantime.

**Comment by star-szr** [comment]
1.2.1 is out now and contains this fix and a couple others.
