### ISSUE TITLE
https://dreditor.org/ not working

### ISSUE THREAD

**Issue by scor** [unicorn-fail/dreditor#58]
I was on d.o (https) and got a popup message offering me to download the latest version of dreditor over at https://dreditor.org/. I clicked yes and was redirected to https://dreditor.org/ which doesn't work. (the http URL works but not the https). that was in FF.

**Comment by kostajh** [comment]
I'm also getting this message to download the latest version, even though I am using the latest (1.2.1).

**Comment by scor** [comment]
yes, I also received this message after downloading the latest today, but I thought that might be a glitch.

**Comment by markhalliwell** [comment]
https://dreditor.org now has an SSL cert and configured properly. @kostajh, I haven't seen this. Please let me know if you see it again by opening a new issue.

**Comment by star-szr** [comment]
@kostajh It's also possible that you have two versions of Dreditor installed, especially if you're on Chrome.

**Comment by markhalliwell** [comment]
Committed 97f84677ebceaedd1f3728c4e38d6d3c3ee9c897 which fixes the open window to explicitly define https as the default instead of being protocol relative.
