### ISSUE TITLE
Unbury issue tags

### ISSUE THREAD

**Issue by xjm** [unicorn-fail/dreditor#63]
Following the d.o D7 upgrade, the issue tags are nigh-on impossible to find.

![tags_glhf](https://f.cloud.github.com/assets/1369057/1484340/c6bd0900-4705-11e3-9192-3736a4b8636a.png)

 Previously, dreditor surfaced this field by uncollapsing it and removing the extra fieldset wrapping (and maybe also by moving it up the form). Let's reimplement that. :)

![tags_are_metadata](https://f.cloud.github.com/assets/1369057/1484344/d7ee5d50-4705-11e3-99e5-9af0a1ea021d.png)

See also:
https://drupal.org/node/2120043
https://drupal.org/node/355257
https://drupal.org/node/1212586
https://drupal.org/node/1167282

**Comment by xjm** [comment]
See also: https://github.com/dreditor/dreditor/issues/27

**Comment by Bojhan** [comment]
I remember opening an issue about this back in 2011 and also when they set out with this redesign, as far as I remember was it always like this. 

It is really annoying though, hope Dreditor can fix this.

**Comment by joachim-n** [comment]
One reason to not make the tags too obvious is that far too many users go crazy with the pointless tags.

tags, users, pointless, pointless tags, users tagging issues, dreditor, my cat

**Comment by markhalliwell** [comment]
This is actually no longer moved by Dreditor and is part of the d.o infra:
https://drupal.org/node/2120043
