### ISSUE TITLE
Hide the filter tips when editing an issue

### ISSUE THREAD

**Issue by xjm** [unicorn-fail/dreditor#64]
People who use dreditor know how to enter filtered HTML. It's just even more noise on the noisier-than-ever issue form.

![hide_filter_tips](https://f.cloud.github.com/assets/1369057/1484504/c80cda5e-4707-11e3-8aee-803f44748d34.png)

**Comment by xjm** [comment]
I guess we could also collapse it on a user toggle or something if removing it outright is too mean.

**Comment by dawehner** [comment]
+2

**Comment by sun** [comment]
The old issue summary Ajax behavior/app contains some related code (which no longer applies):

``` js
          // For users with just one input format, wrap filter tips in a fieldset.
          // @todo Abstract this into a behavior. Also applies to comment form.
          $widget.find('fieldset > ul.tips')
            .wrap('<fieldset class="collapsible collapsed"></fieldset>')
            .before('<legend>Input format</legend>');
```

This needs to be completely re-thought, since the text format widget looks + feels + works completely different in D7.

**Comment by Bojhan** [comment]
I would promote doing something like https://drupal.org/node/2098071 

I simply have display:none; on this. As expert user, I really rarely actually need this.

**Comment by YesCT** [comment]
can we replace it with just the link https://drupal.org/filter/tips ?

I often point out to people the info there about [#NNNNN]

**Comment by helmo** [comment]
+1 for collapsing

**Comment by markhalliwell** [comment]
Fixed with https://drupal.org/node/2104275
