### ISSUE TITLE
Cant copy code from dreditor anymore

### ISSUE THREAD

**Issue by ParisLiakos** [unicorn-fail/dreditor#65]
After d.o d7 upgrade i can no longer copy code from inside dreditor.

Thas annoying, i have to open the file in a new tab to actually copy stuff

**Comment by damiankloip** [comment]
+1 on fixing this :) I have noticed the same issue...

**Comment by markhalliwell** [comment]
Code was previously introduced in a partial attempt to fix #37. It wasn't fully finished and I will likely fix it this weekend to allow a meta key (ctrl,alt,cmd) to be pressed one select actual code from the review window.

**Comment by damiankloip** [comment]
Great, sound good to me. Thanks Mark!
