### ISSUE TITLE
Patch presented incorrectly (newline is missing)

### ISSUE THREAD

**Issue by wimleers** [unicorn-fail/dreditor#7]
Actual patch hunk:

```
@@ -276,7 +284,19 @@ public static function baseFieldDefinitions($entity_type) {
       'description' => t('The revision log message.'),
       'type' => 'string_field',
     );
+    $properties['changed'] = array(
+      'label' => t('Changed'),
+      'description' => t('The time that the custom block was last edited.'),
+      'type' => 'integer_field',
+    );
     return $properties;
   }

+  /**
+   * {@inheritdoc}
+   */
+  public function getChangedTime() {
+    return $this->get('changed')->value;
+  }
+
 }
```

Presented as: 
![screen shot 2013-09-03 at 15 55 47](https://f.cloud.github.com/assets/14240/1073094/9f0db540-14a0-11e3-8395-76d62d46e099.png)

Note how dreditor makes it look like there is _no_ newline before the new `getChangedTime()` method.

See it for yourself right here: https://drupal.org/node/2074193#comment-7822281

**Comment by wimleers** [comment]
Oh, and it does _not_ happen in a very similar patch right here: https://drupal.org/node/2074229#comment-7817707 — same `getChangedTime()` addition!

**Comment by markhalliwell** [comment]
That is very odd indeed.... I'll have to take a look into this when I have the time. Marking this for 2.0 (lowest priority atm).

**Comment by wimleers** [comment]
Yes, definitely a low priority :)
