### ISSUE TITLE
Upgrade plain comment to issue update

### ISSUE THREAD

**Issue by helmo** [unicorn-fail/dreditor#70]
Sometimes you start on a comment and then realize that more needs to be done... so a click on "Update this issue". 

Wouldn't it be nice if the text in the comment textarea was automatically transferred to the edit form?

Just a wild idea...
Label: enhancement

**Comment by sun** [comment]
https://drupal.org/node/2159813 has just been fixed, so the issue edit form is back on the node view page, which makes this issue obsolete, I guess.
