### ISSUE TITLE
Can't see the Recent Files Names

### ISSUE THREAD

**Issue by gmclelland** [unicorn-fail/dreditor#71]
When viewing https://drupal.org/node/1772212 or any issue, I can't see the file name and link.  It gets cutoff.

![transition effect in fullscreen theme 1772212 drupal org 2013-11-12 12-47-12](https://f.cloud.github.com/assets/40570/1524746/df6778cc-4bca-11e3-873b-2d9e35f24457.jpg)

I'm using Chrome 30 on a Mac. 

I'm surprised more people have reported this.  Note: some page like https://drupal.org/node/1792738 appear just fine.

Adding this seems to fix it.

``` css
.dreditor-pift-processed{
  width:100%;
}
```

Hope that helps

**Comment by star-szr** [comment]
Thanks for the report! Please see #56. The fix for this will be in the next release of Dreditor, and you can test it at http://dreditor.org/development.
