### ISSUE TITLE
Paste fails to do anything - large review lost

### ISSUE THREAD

**Issue by rfay** [unicorn-fail/dreditor#74]
I did a significant review of https://drupal.org/node/2134257 and then did a paste... nothing happened. I found no way to resolve it. So I opened a new window and went through and did it again with dreditor, copying and pasting my still accessible comments in the new dreditor session. (First, I tried a trivial comment and paste... that worked OK). Finally, I tried pasting again and was back where I started. Dead in the water, with the review lost.

Chrome 31.0.1650.48 on Macos Mtn Lion, dreditor 1.2.3

**Comment by markhalliwell** [comment]
This issue doesn't seem to have any logic, but rather occurs rather randomly. I have "fixed" this (or so I thought) several times, but the cause was always different. Unfortunately just knowing that it happened on a particular issue doesn't really help pin point the issue. What were ther console errors?

**Comment by rfay** [comment]
```
Uncaught TypeError: Cannot call method 'compareDocumentPosition' of undefined VM153:56
sortOrder VM153:56
Drupal.dreditor.patchReview.sort VM153:945
Drupal.dreditor.patchReview.paste VM153:951
(anonymous function) VM153:1475
c.event.handle js_xAPl0qIk9eowy_iS9tNkCWXLUVoat94SQT48UBCFkyQ.js:64
h.handle.o js_xAPl0qIk9eowy_iS9tNkCWXLUVoat94SQT48UBCFkyQ.js:57
```

**Comment by rfay** [comment]
FYI, I still have this in the browser if there's any other diagnostic you'd like.

**Comment by dawehner** [comment]
I had the same problem when reviewing https://drupal.org/node/2021779#comment-8230509 (maybe that helps to track it down)

**Comment by Gaelan** [comment]
Dreditor should try to detect exceptions from paste and fall back to the user C/Ping.

**Comment by markhalliwell** [comment]
@Gaelan, yes. I agree that there should better handling of errors in Dreditor. FWIW and semi-related: #151
