### ISSUE TITLE
Review button displays same patch for different comments

### ISSUE THREAD

**Issue by colans** [unicorn-fail/dreditor#76]
Over at [Workflows not imported with Features](https://drupal.org/comment/7298720#comment-7298720) for example, when I hit the Review button next to comment 10, I see the patch for it.  If I then hit Esc, and click on the patch for comment 13, I still see the patch for comment 10 when I should see the one for 13.

I can get around this by clicking on the "Cancel" button after I hit Esc.

This may be related to #24, but that deals with hiding things, which I'm not doing.

**Comment by markhalliwell** [comment]
Yes this is a dup of #24. `Esc` is hiding it.
