### ISSUE TITLE
Chrome extension alerting "Dreditor got improved!"

### ISSUE THREAD

**Issue by star-szr** [unicorn-fail/dreditor#8]
I'm getting "Dreditor got improved! Visit the project page to update?" alerts once in a while when using the Chrome extension. Since the Chrome extension auto-updates, this code should be removed. I've confirmed that I don't have the userscript still loading, this code is in the extension folder.

If we are keeping this code for the userscript version, it may need a refactor to point to GitHub commit log.

**Comment by markhalliwell** [comment]
Yes, this is planned for the 2.0.0-rc1 milestone. Much work needs to be done to get it to this point though. It's an _unfortunate_ side effect.
