### ISSUE TITLE
Fixed issues are not all hidden

### ISSUE THREAD

**Issue by mikeryan776** [unicorn-fail/dreditor#81]
Since I reinstalled dreditor at some point after the d.o upgrade to D7, I find when viewing issue queues it hides some but not all Fixed issues. For example, at this moment when I visit https://drupal.org/project/issues/2105305?categories=All it reports "21 fixed issues" as hidden, but on the page 13 fixed issues are displayed. Clicking "Show all issues" shows 34 fixed issues.

**Comment by markhalliwell** [comment]
This is likely an issue with https://drupal.org/node/2140231

**Comment by markhalliwell** [comment]
Actually the filtered issues is "works as designed". Issues that have updated or new comments are ignored (so you can read them, naturally). I added a "mark all as read" button at the top to help alleviate this issue.
