### ISSUE TITLE
Multiple instance of review /simpleytest.me buttons

### ISSUE THREAD

**Issue by vijaycs85** [unicorn-fail/dreditor#90]
Not sure whether it is specific case or not:
1. Updated a comment with patch on an issue
2. Edit comment with Ctrl+Click
3. Refresh the main issue 

Expected:
All patch should have one review & simplytest.me buttons

Actual:
Multiple set of review & simplytest.me buttons
![screen shot 2013-12-09 at 21 46 48](https://f.cloud.github.com/assets/1220029/1709263/de0aedd6-611b-11e3-8306-bf536fe87499.png)

**Comment by markhalliwell** [comment]
This is due to https://drupal.org/node/2125741 just being deployed. A new version of Dreditor will be out in a few hours.
