### ISSUE TITLE
install link has gone

### ISSUE THREAD

**Issue by joachim-n** [unicorn-fail/dreditor#92]
It's possible I'm being stupid, but I can't see where on https://dreditor.org/ I am meant to click to install the new version!

My current dreditor tells me I should upgrade.
I click OK in the popup.
I get taken to https://dreditor.org/
The page says 'Determining latest release'.... and then 'A new version is available'

The text is not clickable.

**Comment by star-szr** [comment]
Browser and OS please :) and any info about which version of Dreditor and how you installed it?

**Comment by joachim-n** [comment]
Firefox 25, Mac OS 10.6.

I am on dreditor 1.2.3, and it's telling me 1.2.4 is available.
![dreditor-no-link](https://f.cloud.github.com/assets/105262/1714272/664bb2d4-619e-11e3-8427-5b0a618505d8.png)

**Comment by star-szr** [comment]
That was an accident for the record ^ :)

**Comment by markhalliwell** [comment]
Uninstall the GM script

Typos courtesy of Siri

**Comment by RoSk0** [comment]
Same issue for me: can't click on install button - it disabled. FF 25.0.1, GM 1.12, Ubuntu 13.10.
Any suggestions?

**Comment by markhalliwell** [comment]
Fixed with https://github.com/dreditor/dreditor.org/commit/4cbe1a14c981e743d05e8ea4a3bb3c14b039583c
![uninstall](https://www.monosnap.com/image/yVixHldGLwxsBbh99ip56TAcr.png)

**Comment by joachim-n** [comment]
I see that message as in the last comment.

Does 1.2.3 really count as an 'old version'? Will every update of dreditor require manual removal of the previous version?

**Comment by markhalliwell** [comment]
Yes. I've actually updated the verbiage already to reflect what it is actually that you need to remove. And no, once you update to a FF XPI extension, you will be able to just click it again when an update is available. Auto updates are still being worked on.
![old](https://www.monosnap.com/image/HkaMAFTD39yVdzzbrC8uXcIdE.png)

**Comment by hansfn** [comment]
Maybe the switch from GreaseMonkey user script to FF extension should be stated clearly somewhere on https://dreditor.org - maybe put something like the text below on https://dreditor.org/about

<blockquote>Dreditor used to be a GreaseMonkey user script, but is now a proper browser extension [...]</blockquote>

I'm a FF user - not sure if the change is the same for the other browsers.

**Comment by joachim-n** [comment]
Does that mean I can remove Greasemonkey? That could do to be said somewhere.

**Comment by hansfn** [comment]
Yes, if Dreditor was the only Greasemonkey script you were using.
