### ISSUE TITLE
fix embed image button

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#96]
the image embed button was really nice.
after the d.o upgrade, the image embed button is missing.

add it back (it might still be there, but just be a little broke)

this is an old screenshot, but it has the button in it:
![writeup](https://f.cloud.github.com/assets/1970586/2015421/def1f928-87b9-11e3-8a5f-59c71070e7ed.png)

**Comment by sun** [comment]
Based on my testing on latest code, the embed button works correctly now.  Let me know if I'm mistaken.

Note that #102 fixed the position/placement of these buttons, which will be part of the next release.
